class Main {
  static main(String[] args) {
    def chitter = new Chitter()
    println(chitter.getActiveUser())
    println(chitter.getUsersSignedUp().getListofUsers())
    chitter.login('Spike')
    println('active '  + chitter.getActiveUser())
    println('active name '  + chitter.getActiveUser().getName())
    println('users ' + chitter.getUsersSignedUp())
    println('users ' + chitter.getUsersSignedUp().getListofUsers())
    chitter.logOut()
    println(chitter.getActiveUser())
    // println('active name '  + chitter.getActiveUser().getName())
    println(chitter.getUsersSignedUp())
    println('users ' + chitter.getUsersSignedUp().getListofUsers())
    chitter.login('Leo')
    println(chitter.getActiveUser())
    println('active name '  + chitter.getActiveUser().getName())
    println(chitter.getUsersSignedUp())
    println('users ' + chitter.getUsersSignedUp().getListofUsers())
    chitter.logOut()
    chitter.login('Spike')
    println(chitter.getActiveUser())
    println('active name '  + chitter.getActiveUser().getName())
    println(chitter.getUsersSignedUp())
    println('users ' + chitter.getUsersSignedUp().getListofUsers())
  }
}
